using System;
using MongoDB.Bson;

namespace GettingStartedWithMongoDB
{
    public class Employee
    {
        /// <summary>
        /// Aggregate roots need an ID. The standard ID type is ObjectID. This field
        /// is generated by Mongo when you insert the object into the database
        /// </summary>
        public ObjectId Id { get; set; }

        public string Name { get; set; }

        public int MonthlyIncome { get; set; }

        public DateTime BirthDate { get; set; }

        public Department Department { get; set; }

        /// <summary>
        /// If you are using multiple constructors, don't forget that t
        /// he aggregate root needs to also have a default constructor. 
        /// </summary>
        protected Employee()
        {
            
        }

        public Employee(String name, DateTime birthDate, int monthlyIncome, Department department)
        {
            this.Name = name;
            this.BirthDate = birthDate;
            this.MonthlyIncome = monthlyIncome;
            this.Department = department;
        }
    }

    public enum Department
    {
        HumanResources,
        Manufacturing,
        Management
    }
}
